### PR TITLE
Add tests for plists

### PR DESCRIPTION
**Pull request by finestructure**
I've come across your project via the swift mailing lists looking for a solution to decode plists with subtrees of unknown format. Thanks a lot for making it available, I feel like this might allow me to solve that problem eventually.

I plugged AnyCodable into my project and unfortunately it doesn't quite work to decode my plist files. The error I'm getting is

```
XCTAssertNoThrow failed: threw error "⚠️ [DecodingError.dataCorrupted: Invalid value cannot be decoded]"
```

(Edit: I initially posted a different looking error from the one the test `testPlistFile` spits out but now went back to my project to confirm they're essentially the same.)

In order to figure out whether it's a problem with how I'm integrating `AnyCodable` or maybe something related to `AnyCodable`, while encoding agnostic in principle, perhaps still being JSON specific, I've added some plist specific tests to the suite.

It turns out that the decoding works fine if the encoding also happens via `AnyCodable` (see the two tests).

However where it fails is in the test `testPlistFile` where I'm trying to decode a simple binary plist file I've added to the project, similar to the mock data used for the JSON tests.

The error is

```
/Users/sas/Projects/GitHub/AnyCodable/Tests/AnyCodableTests/AnyCodableTests.swift:141: error: -[AnyCodableTests.AnyCodableTests testPlistFile] : XCTAssertNoThrow failed: threw error "dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "Invalid value cannot be decoded", underlyingError: nil))" - 
```

I've also tried the xml plist format but am getting the same error.

I wanted to push these tests up while I'm trying to figure out what's going on. Maybe you've got an idea? I'm pretty new to the Codable internals and currently at a loss as to what might be going on.

PS: I've seen that there are some newer branches in the repo as well and I've run these tests on top of both. In one of them all three tests fails, in the other only `testPlistFile`.

PPS: These tests will fail on Linux, because `PropertyListDecoder` [is not available there](https://finestructure.co/blog/2018/10/7/make-propertylistdecoder-available-on-linux). In my project I'm dropping in an implementation to provide it on Linux. Happy to add that as well if it helps by I didn't want to muddy this PR with it.

### CODE REVIEW

**Comment by finestructure** [comment]
Update: I've now managed to successfully read my plist file with `AnyCodable`. The issue was a `Data` field. I'm now simply parsing that out instead of handing it to `AnyCodable` (along side some other fields that it presumably could handle):

```
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Bool.self) {
            self = .bool(v)
            return
        }
        if let v = try? container.decode(Int.self) {
            self = .int(v)
            return
        }
        if let v = try? container.decode(String.self) {
            self = .string(v)
            return
        }
        if let v = try? container.decode(Data.self) {
            self = .data(v)
            return
        }
        if let v = try? container.decode(AnyCodable.self) {
            self = .opaque(v)
            return
        }
        throw ShortcutError.decodingError("Decoding Error: \(dump(container))")
    }
```

Not sure if that's because `Data` fields aren't intended to be handled by `AnyCodable` or if it's something specific to my files.

**Comment by valeriomazzeo** [comment]
`AnyCodable` decoding tries to guess what data type is trying to decode using a fuzzy initialiser.
See https://github.com/asensei/AnyCodable/blob/master/Sources/AnyCodable/AnyCodable.swift#L50.

I am not sure it's possible to "guess" decode `Data`, as most of the other types can be represented as `Data` itself.

**Comment by valeriomazzeo** [comment]
`AnyCodable` decoding tries to guess what data type is trying to decode using a fuzzy initialiser.
See https://github.com/asensei/AnyCodable/blob/master/Sources/AnyCodable/AnyCodable.swift#L50.

I am not sure it's possible to "guess" decode `Data`, as most of the other types can be represented as `Data` itself.

**Comment by valeriomazzeo** [comment]
`AnyCodable` decoding tries to guess what data type is trying to decode using a fuzzy initialiser.
See https://github.com/asensei/AnyCodable/blob/master/Sources/AnyCodable/AnyCodable.swift#L50.

I am not sure it's possible to "guess" decode `Data`, as most of the other types can be represented as `Data` itself.

**Comment by valeriomazzeo** [comment]
`AnyCodable` decoding tries to guess what data type is trying to decode using a fuzzy initialiser.
See https://github.com/asensei/AnyCodable/blob/master/Sources/AnyCodable/AnyCodable.swift#L50.

I am not sure it's possible to "guess" decode `Data`, as most of the other types can be represented as `Data` itself.

Also, I am not sure that `AnyCodable` honours custom encoding/decoding strategies, so that's something to bear in mind.

**Comment by valeriomazzeo** [comment]
`AnyCodable` decoding tries to guess what data type is trying to decode using a fuzzy initialiser.
See https://github.com/asensei/AnyCodable/blob/master/Sources/AnyCodable/AnyCodable.swift#L50.

I am not sure it's possible to "guess" decode `Data`, as most of the other types can be represented as `Data` itself.

Also, I am not sure that `AnyCodable` honours custom encoding/decoding strategies, so that's something to bear in mind.

**Comment by valeriomazzeo** [comment]
`AnyCodable` decoding tries to guess what data type is trying to decode using a fuzzy initialiser.
See https://github.com/asensei/AnyCodable/blob/master/Sources/AnyCodable/AnyCodable.swift#L50.

I am not sure it's possible to "guess" decode `Data`, as most of the other types can be represented as `Data` itself.

Also, I am not sure that `AnyCodable` honours custom encoding/decoding strategies, so that's something to bear in mind.

**Comment by valeriomazzeo** [comment]
`AnyCodable` decoding tries to guess what data type is trying to decode using a fuzzy initialiser.
See https://github.com/asensei/AnyCodable/blob/master/Sources/AnyCodable/AnyCodable.swift#L50.

I am not sure it's possible to "guess" decode `Data`, as most of the other types can be represented as `Data` itself.

Also, I am not sure that `AnyCodable` honours custom encoding/decoding strategies, so that's something to bear in mind.

**Comment by valeriomazzeo** [comment]
`AnyCodable` decoding tries to guess what data type is trying to decode using a fuzzy initialiser.
See https://github.com/asensei/AnyCodable/blob/master/Sources/AnyCodable/AnyCodable.swift#L50.

I am not sure it's possible to "guess" decode `Data`, as most of the other types can be represented as `Data` itself.

Also, I am not sure that `AnyCodable` honours custom encoding/decoding strategies, so that's something to bear in mind.

**Comment by valeriomazzeo** [comment]
`AnyCodable` decoding tries to guess what data type is trying to decode using a fuzzy initialiser.
See https://github.com/asensei/AnyCodable/blob/master/Sources/AnyCodable/AnyCodable.swift#L50.

I am not sure it's possible to "guess" decode `Data`, as most of the other types can be represented as `Data` itself.

Also, I am not sure that `AnyCodable` honours custom encoding/decoding strategies, so that's something to bear in mind.

**Comment by valeriomazzeo** [comment]
`AnyCodable` decoding tries to guess what data type is trying to decode using a fuzzy initialiser.
See https://github.com/asensei/AnyCodable/blob/master/Sources/AnyCodable/AnyCodable.swift#L50.

I am not sure it's possible to "guess" decode `Data`, as most of the other types can be represented as `Data` itself.

Also, I am not sure that `AnyCodable` honours custom encoding/decoding strategies, so that's something to bear in mind.

**Comment by valeriomazzeo** [comment]
`AnyCodable` decoding tries to guess what data type is trying to decode using a fuzzy initialiser.
See https://github.com/asensei/AnyCodable/blob/master/Sources/AnyCodable/AnyCodable.swift#L50.

I am not sure it's possible to "guess" decode `Data`, as most of the other types can be represented as `Data` itself.

Also, I am not sure that `AnyCodable` honours custom encoding/decoding strategies, so that's something to bear in mind.

**Comment by finestructure** [comment]
Ah right, that makes sense, thinking about it. I’ll close this PR then as I guess the tests are not adding much value.

**Pull request closed without merging**
